name: Build firmware and release

on:
  workflow_dispatch:
      inputs:
        tag:
          description: "Firmare version (Tag)"
          required: true
          default: '*.*.*'

jobs:
  release:

    runs-on: ubuntu-latest

    env:
      TMPDIR: /tmp

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO build on selected platforms
      run: |
        pio run -e esp32dev
        pio run -t buildfs -e esp32dev

    - name: Copy binary files
      run: |
        rm -rf ./firmware/esp32dev/*
        echo ${{ github.event.inputs.tag }} > ./firmware/esp32dev/version.txt
        python ~/.platformio/packages/tool-esptoolpy/esptool.py --chip esp32 merge_bin \
                                                                -o ./firmware/esp32dev/esp32dev-${{ github.event.inputs.tag }}-firmware.bin \
                                                                --flash_mode dio \
                                                                --flash_freq 80m \
                                                                --flash_size 4MB \
                                                                0x1000 ~/.platformio/packages/framework-arduinoespressif32/tools/sdk/bin/bootloader_dio_80m.bin \
                                                                0x8000 /tmp/PedalinoMini/build/esp32dev/partitions.bin \
                                                                0xe000 ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin \
                                                                0x10000 /tmp/PedalinoMini/build/esp32dev/firmware.bin \
                                                                0x3c0000 /tmp/PedalinoMini/build/esp32dev/spiffs.bin
        cp ./manifest/template_esp32.json ./firmware/esp32dev/esp32dev-${{ github.event.inputs.tag }}.json
        sed -i 's/x.y.z/${{ github.event.inputs.tag }}/g' ./firmware/esp32dev/esp32dev-${{ github.event.inputs.tag }}.json
        sed -i 's/xxx/esp32doit-devkit-v1/g'              ./firmware/esp32dev/esp32dev-${{ github.event.inputs.tag }}.json
        md5sum /tmp/PedalinoMini/build/esp32dev/firmware.bin | head -c 32 > ./firmware/esp32dev/firmware.bin.md5

    - name: Commit and push firmware ${{ github.event.inputs.tag }} files
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Release firmware ${{ github.event.inputs.tag }}"
        git push origin HEAD:master
        git tag ${{ github.event.inputs.tag }}
        git push --tags

    - name: Create release ${{ github.event.inputs.tag }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
